name: raksneaker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  encrypt: ^5.0.3
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  local_auth: ^2.3.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  http: ^1.2.2
  image_picker: ^1.1.2
  # Maps & Geolocation
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MaterialDesignIcons
      fonts:
        - asset: packages/material_design_icons_flutter/fonts/materialdesignicons-webfont.ttf
