// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is manually written to avoid build_runner dependency
// Matches the structure generated by hive_generator for JadwalModel

part of 'jadwal_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class JadwalModelAdapter extends TypeAdapter<JadwalModel> {
  @override
  final int typeId = 2;

  @override
  JadwalModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return JadwalModel(
      id: fields[0] as String,
      namaSepatu: fields[1] as String,
      merekSepatu: fields[2] as String,
      tanggalWaktu: fields[3] as DateTime,
      keterangan: fields[4] as String,
      createdAt: fields[5] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, JadwalModel obj) {
    writer
      ..writeByte(6)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.namaSepatu)
      ..writeByte(2)
      ..write(obj.merekSepatu)
      ..writeByte(3)
      ..write(obj.tanggalWaktu)
      ..writeByte(4)
      ..write(obj.keterangan)
      ..writeByte(5)
      ..write(obj.createdAt);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JadwalModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
