// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is manually written to avoid build_runner dependency
// Matches the structure generated by hive_generator for KoleksiModel

part of 'koleksi_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class KoleksiModelAdapter extends TypeAdapter<KoleksiModel> {
  @override
  final int typeId = 3;

  @override
  KoleksiModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return KoleksiModel(
      id: fields[0] as String,
      namaSepatu: fields[1] as String,
      merek: fields[2] as String,
      harga: (fields[3] as num).toDouble(),
      keterangan: fields[4] as String,
      images: (fields[5] as List).cast<String>(),
      createdAt: fields[6] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, KoleksiModel obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.namaSepatu)
      ..writeByte(2)
      ..write(obj.merek)
      ..writeByte(3)
      ..write(obj.harga)
      ..writeByte(4)
      ..write(obj.keterangan)
      ..writeByte(5)
      ..write(obj.images)
      ..writeByte(6)
      ..write(obj.createdAt);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KoleksiModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
